"use client";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Container from "react-bootstrap/esm/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <Container style={{ minHeight: "calc(100vh - 120px)" }}>
          {children}
        </Container>

        <Footer />
      </body>
    </html>
  );
}
